name: Cross-Browser Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install playwright pytest
        playwright install ${{ matrix.browser }}
        playwright install-deps

    - name: Run tests
      env:
        PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
      run: |
        pytest --html=report-${{ matrix.browser }}.html

    - uses: actions/upload-artifact@v4
      with:
        name: report-${{ matrix.browser }}
        path: report-${{ matrix.browser }}.html