name: Cross-Browser Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright pytest pytest-html pytest-playwright

    - name: Install browsers
      run: |
        playwright install ${{ matrix.browser }}
        playwright install-deps

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run tests
      env:
        BROWSER: ${{ matrix.browser }}
      run: |
        pytest --html=reports/report-$BROWSER.html -n auto

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/