name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Обновите checkout до v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Обновите setup-python до v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload test report
      uses: actions/upload-artifact@v3.1.2  # Укажите конкретную версию
      with:
        name: test-report
        path: report.html