name: Cross-Browser Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev libnss3 libatk1.0-0 libatk-bridge2.0-0 libxkbcommon-x11-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright pytest pytest-html pytest-xdist

    - name: Install Playwright browsers
      run: |
        npx playwright install ${{ matrix.browser }} --with-deps
        npx playwright install

    - name: Verify Playwright installation
      run: |
        npx playwright --version
        ls -la ~/.cache/ms-playwright/

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run tests
      env:
        BROWSER: ${{ matrix.browser }}
      run: |
        pytest --html=reports/report-$BROWSER.html -n 2

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/